name = "gateopener"
main = "src/worker.js"
workers_dev = true
compatibility_date = "2025-06-23"

[[routes]]
pattern = "gateopener.momu54.me"
zone_name = "momu54.me"
custom_domain = true

[observability]
enabled = true
